
from fastapi import APIRouter, Depends, Query
from fastapi.responses import HTMLResponse
from sqlalchemy.orm import Session
from .database import get_db
from .models import Store
from .finance_models import SellerInvoice, SellerCommissionLedger, SellerInvoicePayment
from .sr_localization import status_sr, money_sr, date_sr
router = APIRouter(tags=["V69 Finansijski izveštaji"])
def _invoice_row(inv: SellerInvoice, seller: Store | None = None):
    return {"id":inv.id,"broj_racuna":inv.invoice_number,"seller_id":inv.seller_id,"partner":seller.name if seller else f"Partner #{inv.seller_id}","status":inv.status,"status_sr":status_sr(inv.status),"ukupno":inv.total_amount,"placeno":inv.amount_paid,"dug":inv.amount_due,"valuta":inv.currency,"period_od":date_sr(inv.period_start),"period_do":date_sr(inv.period_end),"dospece":date_sr(inv.due_date)}
@router.get("/api/admin/finance/sr-dashboard")
def sr_dashboard(db: Session = Depends(get_db)):
    invoices=db.query(SellerInvoice).order_by(SellerInvoice.created_at.desc()).all();stores={s.id:s for s in db.query(Store).all()};total=sum(float(i.total_amount or 0) for i in invoices);paid=sum(float(i.amount_paid or 0) for i in invoices);due=sum(float(i.amount_due or 0) for i in invoices);overdue=sum(float(i.amount_due or 0) for i in invoices if i.status=="OVERDUE");by_status={}
    for i in invoices:
        by_status.setdefault(i.status or "UNKNOWN", {"status_sr":status_sr(i.status),"count":0,"dug":0.0});by_status[i.status or "UNKNOWN"]["count"]+=1;by_status[i.status or "UNKNOWN"]["dug"]+=float(i.amount_due or 0)
    return {"naslov":"Finansijski pregled","kpi":{"ukupno_fakturisano":total,"ukupno_placeno":paid,"trenutni_dug":due,"kasni":overdue,"ukupno_fakturisano_sr":money_sr(total),"ukupno_placeno_sr":money_sr(paid),"trenutni_dug_sr":money_sr(due),"kasni_sr":money_sr(overdue)},"statusi":by_status,"najnoviji_racuni":[_invoice_row(i,stores.get(i.seller_id)) for i in invoices[:20]]}
@router.get("/api/admin/finance/seller-statement-sr")
def seller_statement_sr(seller_id:int=Query(...), db:Session=Depends(get_db)):
    seller=db.get(Store,seller_id);invoices=db.query(SellerInvoice).filter(SellerInvoice.seller_id==seller_id).order_by(SellerInvoice.created_at.desc()).all();ledger=db.query(SellerCommissionLedger).filter(SellerCommissionLedger.seller_id==seller_id).order_by(SellerCommissionLedger.created_at.desc()).all();payments=db.query(SellerInvoicePayment).filter(SellerInvoicePayment.seller_id==seller_id).order_by(SellerInvoicePayment.created_at.desc()).all();debit=sum(float(x.amount or 0) for x in ledger if x.direction=="DEBIT");credit=sum(float(x.amount or 0) for x in ledger if x.direction=="CREDIT")
    return {"partner":{"id":seller_id,"naziv":seller.name if seller else f"Partner #{seller_id}"},"saldo":{"debit":debit,"credit":credit,"dug":debit-credit,"dug_sr":money_sr(debit-credit)},"racuni":[_invoice_row(i,seller) for i in invoices],"uplate":[{"id":p.id,"status":status_sr(p.status),"iznos":p.amount,"iznos_sr":money_sr(p.amount,p.currency),"datum":date_sr(p.payment_date or p.received_at)} for p in payments],"ledger":[{"id":x.id,"tip":x.type,"smer":x.direction,"iznos":x.amount,"iznos_sr":money_sr(x.amount,x.currency),"opis":x.description,"datum":date_sr(x.created_at)} for x in ledger]}
REPORTS_HTML="""<!doctype html><html lang="sr"><head><meta charset="utf-8"><title>Sačuvaj Hranu — Finansijski izveštaji</title><meta name="viewport" content="width=device-width, initial-scale=1"><style>body{font-family:Arial;background:#f4f6f2;padding:24px;color:#172017}.card{background:#fff;border:1px solid #dfe7dc;border-radius:16px;padding:18px;margin-bottom:16px}button,input{padding:10px;border-radius:10px;border:1px solid #cfd8cf}button{background:#246b45;color:white;border:none}pre{background:#101820;color:#e6f0e7;padding:14px;border-radius:12px;overflow:auto}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}@media(max-width:900px){.grid{grid-template-columns:1fr}}.kpi{background:white;border:1px solid #dfe7dc;border-radius:16px;padding:18px}</style></head><body><h1>Finansijski izveštaji</h1><div class="card"><button onclick="loadDashboard()">Osveži izveštaj</button> Seller ID <input id="seller" placeholder="seller_id"><button onclick="loadStatement()">Izveštaj partnera</button> <a href="/admin/finance-console">Finansijska konzola</a></div><div id="kpis" class="grid"></div><div class="card"><h2>Podaci</h2><pre id="out">Učitavanje...</pre></div><script>async function api(p){const r=await fetch(p);const t=await r.text();try{return JSON.parse(t)}catch{return t}}function show(x){document.getElementById('out').textContent=JSON.stringify(x,null,2)}async function loadDashboard(){const d=await api('/api/admin/finance/sr-dashboard');document.getElementById('kpis').innerHTML=Object.entries(d.kpi).filter(x=>x[0].endsWith('_sr')).map(x=>'<div class="kpi"><b>'+x[0].replaceAll('_',' ')+'</b><h2>'+x[1]+'</h2></div>').join('');show(d)}async function loadStatement(){const id=document.getElementById('seller').value;if(!id)return show({greska:'Unesi seller_id'});show(await api('/api/admin/finance/seller-statement-sr?seller_id='+id))}loadDashboard()</script></body></html>"""
@router.get("/admin/finansije-izvestaji", response_class=HTMLResponse)
def finance_reports_console_sr(): return HTMLResponse(REPORTS_HTML, headers={"Cache-Control":"no-store, no-cache, max-age=0"})
@router.get("/admin/finance-reports-console-sr", response_class=HTMLResponse)
def finance_reports_console_sr_alias(): return finance_reports_console_sr()
